name: Start TinyCore VM

on:
  push:
    branches:
      - main

jobs:
  run-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu qemu-system-x86 qemu-utils

    # Debugging Step: Verify that QEMU is installed and check the version
    - name: Check QEMU installation
      run: |
        qemu-system-x86_64 --version || echo "QEMU not installed or not found in PATH"
    
    # Debugging Step: Check if the correct QEMU files are in place
    - name: List QEMU system files
      run: ls /usr/bin/qemu-system-x86_64 || echo "QEMU binary not found"

    - name: Download TinyCore ISO
      run: wget http://tinycorelinux.net/11.x/x86/release/Core-current.iso -O tinycore.iso

    - name: Run VM
      run: qemu-system-x86_64 -m 512M -cdrom ./tinycore.iso -boot d -vnc :0
